name: Azure Deploy
on:
  push:
    branches:
      - main
      path:
        - infarstructure/**
    pull_reaquest:
      path:
      - infarstructure/**
    workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    envirement : development
    steps : 
      - uses: actions/checkout@v4
      - name: Azure login 
        uses: azure/login@v2.1.1
        with:
          client-id: ${{secrets.AZURE_CLIONT_ID}}
          tenant-id : ${{secrets.AZURE_TENANT_ID}}
          subscription-id : ${{secrets.AZURE_SUBSCRIPTION_ID}} 
      - uses: Azure/CLI@v2
        with:
          inlineScript : |
            #!/bin/bash
            az group create --name ${{vars.RESOURCE_GROUP_NAME}} --location ${{vars.RESOURCE_GROUP_LOCATION}}
            echo "Azure resource group created with success"
      - name : Deploy
        uses : azure/arm-deploy@v2
        with:
          resourceGroupName : ${{vars.RESSOURCE_GROUP_NAME}}
          template : ./infrastructure/main.bicep
